# 爬取大盤


自從上一堂課開始後，同學開始想要新增新的數據到資料庫，但是其實有點難，

這個單元將會分享如何新增爬蟲，並且將爬蟲加入 Finlab 所提供的 API 中

### 爬蟲的網址

我們想要爬取的網址如下：
http://www.tse.com.tw/zh/page/trading/exchange/MI_5MINS_INDEX.html

### 下載某天的資料

In [2]:
import requests

import datetime

date = datetime.date(2019,1,2)
datestr = date.strftime("%Y%m%d") #改年月日的格式(沒有dash)

# http://www.twse.com.tw/exchangeReport/MI_5MINS_INDEX?response=csv&date=20190102&_=1552616075051
res = requests.get("http://www.twse.com.tw/exchangeReport/MI_5MINS_INDEX?response=csv&date="+datestr+"&_=1552616075051")

res.text[:1000]

'"108年01月02日每5秒指數統計"\r\n"時間","發行量加權股價指數","未含金融保險股指數","未含電子股指數","未含金融電子股指數","水泥類指數","食品類指數","塑膠類指數","紡織纖維類指數","電機機械類指數","電器電纜類指數","化學生技醫療類指數","化學類指數","生技醫療類指數","玻璃陶瓷類指數","造紙類指數","鋼鐵類指數","橡膠類指數","汽車類指數","電子類指數","半導體類指數","電腦及週邊設備類指數","光電類指數","通信網路類指數","電子零組件類指數","電子通路類指數","資訊服務類指數","其他電子類指數","建材營造類指數","航運類指數","觀光類指數","金融保險類指數","貿易百貨類指數","油電燃氣類指數","其他類指數",\r\n="09:00:00","9,727.41","8,145.71","13,851.88","11,683.21","129.81","1,617.70","277.92","505.99","158.99","46.43","91.30","101.94","55.27","34.80","181.71","104.72","242.57","198.27","388.00","151.06","82.61","32.62","122.64","84.80","107.19","91.21","70.82","259.73","64.38","101.40","1,187.56","241.61","138.19","233.55",\r\n="09:00:05","9,725.27","8,143.83","13,835.69","11,664.40","130.10","1,610.65","275.85","506.02","158.99","46.43","91.34","101.94","55.34","34.80","181.74","104.55","242.87","198.27","388.25","151.64","82.79","32.66","120.14","85.09","107.19","91.39","71.20","259.73","64.38","101.41","1,187.38","241.61","138.19","233.98",\r'

### 將資料用pandas整理成表格(dataframe)

Pandas 教學：
http://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

In [35]:
import pandas as pd
import io #虛擬？檔案
#df = pd.read_csv(io.StringIO(res.text)) 匯入成CSV
#.text.replace("","")
df = pd.read_csv(io.StringIO(res.text.replace("=", "")), header=1, index_col='時間') #header 設定第一欄為標籤，時間列為第一列

df[:10]

,發行量加權股價指數,未含金融保險股指數,未含電子股指數,未含金融電子股指數,水泥類指數,食品類指數,塑膠類指數,紡織纖維類指數,電機機械類指數,電器電纜類指數,...,資訊服務類指數,其他電子類指數,建材營造類指數,航運類指數,觀光類指數,金融保險類指數,貿易百貨類指數,油電燃氣類指數,其他類指數,Unnamed: 35
時間,,,,,,,,,,,,,,,,,,,,,
09:00:00,"9,727.41","8,145.71","13,851.88","11,683.21",129.81,"1,617.70",277.92,505.99,158.99,46.43,...,91.21,70.82,259.73,64.38,101.40,"1,187.56",241.61,138.19,233.55,NaN
09:00:05,"9,725.27","8,143.83","13,835.69","11,664.40",130.10,"1,610.65",275.85,506.02,158.99,46.43,...,91.39,71.20,259.73,64.38,101.41,"1,187.38",241.61,138.19,233.98,NaN
09:00:10,"9,730.34","8,147.35","13,845.10","11,670.48",130.69,"1,610.69",275.20,507.66,159.61,46.51,...,91.39,71.34,259.98,64.59,101.41,"1,188.62",241.61,138.19,234.18,NaN
09:00:15,"9,724.78","8,142.20","13,835.07","11,659.45",130.78,"1,612.51",275.24,507.92,159.71,46.51,...,91.39,71.30,260.29,64.58,101.48,"1,188.35",241.69,136.40,234.61,NaN
09:00:20,"9,730.49","8,147.77","13,845.49","11,671.93",130.78,"1,618.77",275.26,508.42,159.87,46.54,...,91.39,71.32,260.67,64.58,101.57,"1,188.39",241.73,137.00,234.62,NaN
09:00:25,"9,731.75","8,148.90","13,846.80","11,673.18",130.78,"1,615.13",275.30,508.86,160.00,46.54,...,91.39,71.30,260.81,64.57,101.57,"1,188.47",241.72,137.01,234.68,NaN
09:00:30,"9,728.81","8,146.37","13,852.32","11,681.17",130.59,"1,619.68",275.72,508.96,160.23,46.62,...,91.66,71.32,261.16,64.58,101.57,"1,188.17",241.73,137.01,234.71,NaN
09:00:35,"9,727.68","8,145.25","13,850.66","11,679.09",130.80,"1,619.62",275.34,508.93,160.25,46.62,...,91.66,71.29,261.41,64.58,101.52,"1,188.18",241.74,137.01,234.76,NaN
09:00:40,"9,728.25","8,146.29","13,849.10","11,678.94",130.80,"1,619.57",275.36,508.90,160.22,46.62,...,91.66,71.29,261.42,64.59,101.53,"1,187.78",241.94,137.01,234.75,NaN
09:00:45,"9,728.95","8,147.03","13,850.33","11,680.66",130.80,"1,619.51",275.56,508.90,160.13,46.62,...,91.66,71.36,261.41,64.62,101.53,"1,187.72",241.94,137.01,234.77,NaN

## 資料處理
1. 去除不需要的行、列
2. 設定index為日期
3. 將逗點「,」刪除，讓table裡面的字串(str)變成數字(float or int)

In [36]:
datestr + ' ' + df.index

Index(['20190102 09:00:00', '20190102 09:00:05', '20190102 09:00:10',
       '20190102 09:00:15', '20190102 09:00:20', '20190102 09:00:25',
       '20190102 09:00:30', '20190102 09:00:35', '20190102 09:00:40',
       '20190102 09:00:45',
       ...
       '20190102 13:29:40', '20190102 13:29:45', '20190102 13:29:50',
       '20190102 13:29:55', '20190102 13:30:00', '20190102 說明:',
       '20190102 民國100年1月16日以前，資料為每一分鐘方式提供。',
       '20190102 民國103年2月23日以前，資料為每15秒方式提供。',
       '20190102 民國103年2月24日以後，資料為每10秒方式提供。',
       '20190102 民國103年12月29日以後，資料為每5秒方式提供。'],
      dtype='object', length=3246)

In [53]:
# 1. 去除不需要的行、列

import pandas as pd
import io
df = pd.read_csv(io.StringIO(res.text.replace("=", "")), header=1, index_col='時間')

df = df.dropna(how='all', axis=0).dropna(how='all', axis=1) #dropna = 刪除資料為空的行跟列、axis = 0(行)1(列)
df[:2]

,發行量加權股價指數,未含金融保險股指數,未含電子股指數,未含金融電子股指數,水泥類指數,食品類指數,塑膠類指數,紡織纖維類指數,電機機械類指數,電器電纜類指數,...,電子通路類指數,資訊服務類指數,其他電子類指數,建材營造類指數,航運類指數,觀光類指數,金融保險類指數,貿易百貨類指數,油電燃氣類指數,其他類指數
時間,,,,,,,,,,,,,,,,,,,,,
09:00:00,"9,727.41","8,145.71","13,851.88","11,683.21",129.81,"1,617.70",277.92,505.99,158.99,46.43,...,107.19,91.21,70.82,259.73,64.38,101.40,"1,187.56",241.61,138.19,233.55
09:00:05,"9,725.27","8,143.83","13,835.69","11,664.40",130.10,"1,610.65",275.85,506.02,158.99,46.43,...,107.19,91.39,71.20,259.73,64.38,101.41,"1,187.38",241.61,138.19,233.98

In [54]:
# 2. 設定index為日期
df.index = pd.to_datetime(datestr + ' ' + df.index)
#處理成電腦看得懂的格式之後

df['2019-01-02 9:00':'2019-1-2 9:00:20'] #用時間呼叫陣列

,發行量加權股價指數,未含金融保險股指數,未含電子股指數,未含金融電子股指數,水泥類指數,食品類指數,塑膠類指數,紡織纖維類指數,電機機械類指數,電器電纜類指數,...,電子通路類指數,資訊服務類指數,其他電子類指數,建材營造類指數,航運類指數,觀光類指數,金融保險類指數,貿易百貨類指數,油電燃氣類指數,其他類指數
2019-01-02 09:00:00,"9,727.41","8,145.71","13,851.88","11,683.21",129.81,"1,617.70",277.92,505.99,158.99,46.43,...,107.19,91.21,70.82,259.73,64.38,101.40,"1,187.56",241.61,138.19,233.55
2019-01-02 09:00:05,"9,725.27","8,143.83","13,835.69","11,664.40",130.10,"1,610.65",275.85,506.02,158.99,46.43,...,107.19,91.39,71.20,259.73,64.38,101.41,"1,187.38",241.61,138.19,233.98
2019-01-02 09:00:10,"9,730.34","8,147.35","13,845.10","11,670.48",130.69,"1,610.69",275.20,507.66,159.61,46.51,...,107.46,91.39,71.34,259.98,64.59,101.41,"1,188.62",241.61,138.19,234.18
2019-01-02 09:00:15,"9,724.78","8,142.20","13,835.07","11,659.45",130.78,"1,612.51",275.24,507.92,159.71,46.51,...,107.43,91.39,71.30,260.29,64.58,101.48,"1,188.35",241.69,136.40,234.61
2019-01-02 09:00:20,"9,730.49","8,147.77","13,845.49","11,671.93",130.78,"1,618.77",275.26,508.42,159.87,46.54,...,107.61,91.39,71.32,260.67,64.58,101.57,"1,188.39",241.73,137.00,234.62

In [59]:
# 3. 將逗點「,」刪除，讓table裡面的字串(str)變成數字(float or int)
df.dtypes #用dtypes查看資料型態 (object = 字串, float = 數字)

In [60]:
df.astype(float) #astype 把資料全部轉成數字(但Error會顯示逗號無法轉)

ValueError: could not convert string to float: '9,727.41'

In [41]:
# 3. 將逗點「,」刪除，讓table裡面的字串(str)變成數字(float or int)
df = df.applymap(lambda s: float(str(s).replace(",", "")))
#applymap 把裡面字串中的物件str(s).replace(",", "")逗號取代掉
#在將取代後的float
#Lambda?
df[:10]

,發行量加權股價指數,未含金融保險股指數,未含電子股指數,未含金融電子股指數,水泥類指數,食品類指數,塑膠類指數,紡織纖維類指數,電機機械類指數,電器電纜類指數,...,電子通路類指數,資訊服務類指數,其他電子類指數,建材營造類指數,航運類指數,觀光類指數,金融保險類指數,貿易百貨類指數,油電燃氣類指數,其他類指數
2019-01-02 09:00:00,9727.41,8145.71,13851.88,11683.21,129.81,1617.70,277.92,505.99,158.99,46.43,...,107.19,91.21,70.82,259.73,64.38,101.40,1187.56,241.61,138.19,233.55
2019-01-02 09:00:05,9725.27,8143.83,13835.69,11664.40,130.10,1610.65,275.85,506.02,158.99,46.43,...,107.19,91.39,71.20,259.73,64.38,101.41,1187.38,241.61,138.19,233.98
2019-01-02 09:00:10,9730.34,8147.35,13845.10,11670.48,130.69,1610.69,275.20,507.66,159.61,46.51,...,107.46,91.39,71.34,259.98,64.59,101.41,1188.62,241.61,138.19,234.18
2019-01-02 09:00:15,9724.78,8142.20,13835.07,11659.45,130.78,1612.51,275.24,507.92,159.71,46.51,...,107.43,91.39,71.30,260.29,64.58,101.48,1188.35,241.69,136.40,234.61
2019-01-02 09:00:20,9730.49,8147.77,13845.49,11671.93,130.78,1618.77,275.26,508.42,159.87,46.54,...,107.61,91.39,71.32,260.67,64.58,101.57,1188.39,241.73,137.00,234.62
2019-01-02 09:00:25,9731.75,8148.90,13846.80,11673.18,130.78,1615.13,275.30,508.86,160.00,46.54,...,107.60,91.39,71.30,260.81,64.57,101.57,1188.47,241.72,137.01,234.68
2019-01-02 09:00:30,9728.81,8146.37,13852.32,11681.17,130.59,1619.68,275.72,508.96,160.23,46.62,...,107.57,91.66,71.32,261.16,64.58,101.57,1188.17,241.73,137.01,234.71
2019-01-02 09:00:35,9727.68,8145.25,13850.66,11679.09,130.80,1619.62,275.34,508.93,160.25,46.62,...,107.59,91.66,71.29,261.41,64.58,101.52,1188.18,241.74,137.01,234.76
2019-01-02 09:00:40,9728.25,8146.29,13849.10,11678.94,130.80,1619.57,275.36,508.90,160.22,46.62,...,107.58,91.66,71.29,261.42,64.59,101.53,1187.78,241.94,137.01,234.75
2019-01-02 09:00:45,9728.95,8147.03,13850.33,11680.66,130.80,1619.51,275.56,508.90,160.13,46.62,...,107.58,91.66,71.36,261.41,64.62,101.53,1187.72,241.94,137.01,234.77

In [61]:
#1~3 也可以這樣寫

def abc(e):
    ret = str(e)
    ret = ret.replace(",", "")
    ret = float(ret)
    return ret#float(str(e).replace(",", ""))

df = df.applymap(abc)
df.head()

,發行量加權股價指數,未含金融保險股指數,未含電子股指數,未含金融電子股指數,水泥類指數,食品類指數,塑膠類指數,紡織纖維類指數,電機機械類指數,電器電纜類指數,...,電子通路類指數,資訊服務類指數,其他電子類指數,建材營造類指數,航運類指數,觀光類指數,金融保險類指數,貿易百貨類指數,油電燃氣類指數,其他類指數
2019-01-02 09:00:00,9727.41,8145.71,13851.88,11683.21,129.81,1617.70,277.92,505.99,158.99,46.43,...,107.19,91.21,70.82,259.73,64.38,101.40,1187.56,241.61,138.19,233.55
2019-01-02 09:00:05,9725.27,8143.83,13835.69,11664.40,130.10,1610.65,275.85,506.02,158.99,46.43,...,107.19,91.39,71.20,259.73,64.38,101.41,1187.38,241.61,138.19,233.98
2019-01-02 09:00:10,9730.34,8147.35,13845.10,11670.48,130.69,1610.69,275.20,507.66,159.61,46.51,...,107.46,91.39,71.34,259.98,64.59,101.41,1188.62,241.61,138.19,234.18
2019-01-02 09:00:15,9724.78,8142.20,13835.07,11659.45,130.78,1612.51,275.24,507.92,159.71,46.51,...,107.43,91.39,71.30,260.29,64.58,101.48,1188.35,241.69,136.40,234.61
2019-01-02 09:00:20,9730.49,8147.77,13845.49,11671.93,130.78,1618.77,275.26,508.42,159.87,46.54,...,107.61,91.39,71.32,260.67,64.58,101.57,1188.39,241.73,137.00,234.62

### 全部加在一起

In [5]:
# 時間物件
import datetime

# 下載網頁用的
import requests

# 資料處理
import pandas as pd

# 檔案串流
from io import StringIO


# 下載某天的資料

date = datetime.date(2018,1,3)
date_str = date.strftime('%Y%m%d')
res = requests.get("http://www.twse.com.tw/exchangeReport/MI_5MINS_INDEX?response=csv&date=" + 
                   date_str + "&_=1544020420045")

# 利用 pandas 將資料整理成表格

df = pd.read_csv(StringIO(res.text.replace("=","")), header=1, index_col='時間')

# 資料處理

df = df.dropna(how='all', axis=0).dropna(how='all', axis=1)
df.index = pd.to_datetime(date.strftime('%Y %m %d ') + pd.Series(df.index))
df = df.apply(lambda s: s.astype(str).str.replace(",", "").astype(float))

df.head()

,發行量加權股價指數,未含金融保險股指數,未含電子股指數,未含金融電子股指數,水泥類指數,食品類指數,塑膠類指數,紡織纖維類指數,電機機械類指數,電器電纜類指數,...,電子通路類指數,資訊服務類指數,其他電子類指數,建材營造類指數,航運類指數,觀光類指數,金融保險類指數,貿易百貨類指數,油電燃氣類指數,其他類指數
時間,,,,,,,,,,,,,,,,,,,,,
2018-01-03 09:00:00,10710.73,9094.86,14537.98,12469.76,118.30,1650.04,284.81,491.68,195.92,52.67,...,120.67,88.49,101.61,261.65,69.72,134.95,1196.45,238.23,145.33,253.80
2018-01-03 09:00:05,10759.61,9139.70,14553.75,12478.29,118.30,1650.11,285.31,491.65,195.94,53.14,...,120.67,88.51,101.61,261.65,69.97,134.95,1198.94,238.23,145.33,253.80
2018-01-03 09:00:10,10765.54,9144.68,14564.15,12487.82,118.35,1650.11,285.54,492.46,196.11,53.18,...,120.67,88.51,101.86,261.81,70.09,134.95,1199.65,238.23,145.33,253.88
2018-01-03 09:00:15,10775.89,9155.36,14575.94,12504.18,118.35,1648.79,285.58,492.26,196.49,53.18,...,120.79,88.52,101.92,261.95,70.10,134.95,1199.13,239.05,146.53,254.06
2018-01-03 09:00:20,10777.92,9157.53,14577.97,12507.33,118.35,1649.48,285.51,492.88,196.75,53.15,...,120.86,88.51,101.94,262.05,70.13,134.95,1198.96,239.09,146.53,254.09

In [5]:
import pandas as pd

pd.__version__

'0.24.2'

### 有了這個功能後，下一步呢？

下一部我們要將這個資料整合進資料庫喔！

讓資料庫變成超級豐富吧！